### PR TITLE
studio app methods to crop or contain images

### PR DESCRIPTION
**Pull request by patriciacarbajal**
Gives StudioApp methods to set the overflow type image elements to cropped or contained, so we can consolidate the behavior of all of the studio apps.

### CODE REVIEW

**Comment by mnutt** [comment]
Looks great, works great 👍  I'm just curious though, what would be a scenario where we'd manually call `cropImage()` vs Studio just setting the background css properties on the tag during save? Is it something to do with us changing from an `` tag nested inside a `<div>` to just the `<div>` with `background-image` set?

**Comment by snackzone** [comment]
So @mnutt I read your comment last night and was like 🤯

After thinking about it a bunch, here are some thoughts:

When we initially agreed to this task, one of our baseline assumptions was that this logic would need to be handled inside of the Studio Apps themselves (not exported by the tag).

In retrospect, I think this was because we figured that the implementation would entail more than setting 3 CSS properties.

A different way to imagine this implementation would be something like:

- Add select-menu displaying crop / contain options for all `image` type tags. Toggling it updates `backgroundSize`, `backgroundPosition`, and `backgroundRepeat` properties on the `tag` model.
- Update the `style` computed property on the Tag model to add these properties into the inline styles on the html elements
- Remove all existing handling of crop / contain in Studio Apps (since Studio is just setting CSS properties directly)

However, I have a couple issues with this. One is more short-term, and the other is more medium-term (react stuff incoming).

The short-term one is that the tag model is pretty overloaded as is. Adding another section of properties (that's not even relevant for all tags) would probably be grouped under another comment explaining what sets these and what they do. Updating this property is something we will be doing - for example adding a user option position the image within the frame - will add even more complexity to the Studio tag. Not positive, but I'm _pretty_ sure I'd rather update @patriciacarbajal 's implementation here than the tag model.

The medium-term issue is that my proposed alternative involves updating the exported html on the tag. I think moving to a more sophisticated rendering library (React) simplifies the artifact that Studio exports, from an HTML document (with embedded JSON) to just JSON. In that case, Studio-Framework is the rendering library responsible for transforming this JSON and rendering it as HTML. I think this cleans up a lot of things in Studio and helps clarify the contract between Studio and Studio-Framework.

It also leaves the door open to a crazy future where Studio-Framework is only one rendering library for Studio documents - there could be others that produce different types of files other than HTML... although I don't really know what that looks like or if we'd ever do such a thing, the fact that this would be a possibility suggests strongly to me that we are on the right track with how we are separating these concerns.

Soooo TLDR: you are correct and we could have done that, but maybe philosophically that approach is not the best anymore?

Sorry for the big crazy rant!

**Review by spencer516 — APPROVED** [review]

**Comment by mnutt** [comment]
I agree with everything @snackzone mentioned, but to me it seems like it would be roughly the same either way—studio-app gets the functionality for free, while studio-framework needs to enumerate which properties are styles, just as it does now. And it seems like in this case the css properties map pretty closely to the desired behavior.

**Review by spencer516 — APPROVED** [review]

**Comment by mnutt** [comment]
The vast majority of what goes into the Tag model is presentational already, and I think CSS does a reasonable job at being a declarative presentation syntax, with the rather large benefit that it’s well-understood. (or at least there are a lot of articles on it) I wouldn’t be opposed to separating out Tag’s style properties from its behavioral ones, but that doesn’t seem like an argument in favor of not making this particular property a style property.

**Pull request merged**
